/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.avdw.picross.gui;

/**
 *
 * @author CP318674
 */
public class GuiLayout extends javax.swing.JPanel {

    private Integer cellSize;

    private Gui gui;

    /**
     * Creates new form PicrossLayout
     */
    public GuiLayout() {
        initComponents();
    }

    GuiLayout(Gui gui, Integer cellSize) {
        this.gui = gui;
        this.cellSize = cellSize;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        controlColor = new javax.swing.JPanel();
        picrossPanel = new javax.swing.JPanel();
        filler = new javax.swing.JPanel();
        picrossColHint = new net.avdw.picross.gui.PicrossColHint();
        picrossRowHint = new net.avdw.picross.gui.PicrossRowHint();
        picrossView = new net.avdw.picross.gui.PicrossView(gui, cellSize);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout controlColorLayout = new javax.swing.GroupLayout(controlColor);
        controlColor.setLayout(controlColorLayout);
        controlColorLayout.setHorizontalGroup(
            controlColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        controlColorLayout.setVerticalGroup(
            controlColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        add(controlColor, java.awt.BorderLayout.PAGE_END);

        picrossPanel.setLayout(new java.awt.GridLayout(2, 2));

        javax.swing.GroupLayout fillerLayout = new javax.swing.GroupLayout(filler);
        filler.setLayout(fillerLayout);
        fillerLayout.setHorizontalGroup(
            fillerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        fillerLayout.setVerticalGroup(
            fillerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        picrossPanel.add(filler);

        javax.swing.GroupLayout picrossColHintLayout = new javax.swing.GroupLayout(picrossColHint);
        picrossColHint.setLayout(picrossColHintLayout);
        picrossColHintLayout.setHorizontalGroup(
            picrossColHintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        picrossColHintLayout.setVerticalGroup(
            picrossColHintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        picrossPanel.add(picrossColHint);

        javax.swing.GroupLayout picrossRowHintLayout = new javax.swing.GroupLayout(picrossRowHint);
        picrossRowHint.setLayout(picrossRowHintLayout);
        picrossRowHintLayout.setHorizontalGroup(
            picrossRowHintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        picrossRowHintLayout.setVerticalGroup(
            picrossRowHintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        picrossPanel.add(picrossRowHint);

        picrossView.setPreferredSize(preferredSize());

        javax.swing.GroupLayout picrossViewLayout = new javax.swing.GroupLayout(picrossView);
        picrossView.setLayout(picrossViewLayout);
        picrossViewLayout.setHorizontalGroup(
            picrossViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        picrossViewLayout.setVerticalGroup(
            picrossViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        picrossPanel.add(picrossView);

        add(picrossPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel controlColor;
    private javax.swing.JPanel filler;
    private javax.swing.JPanel jPanel5;
    private net.avdw.picross.gui.PicrossColHint picrossColHint;
    private javax.swing.JPanel picrossPanel;
    private net.avdw.picross.gui.PicrossRowHint picrossRowHint;
    private net.avdw.picross.gui.PicrossView picrossView;
    // End of variables declaration//GEN-END:variables
}
