/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.avdw.picross.gui;

import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.LayoutManager;
import net.avdw.picross.api.ACell;

/**
 *
 * @author CP318674
 */
public class PicrossView extends javax.swing.JPanel {

    private final Gui gui;
    private final Integer size;

    /**
     * Creates new form PicrossView
     */
    public PicrossView(Gui gui, Integer size) {
        this.gui = gui;
        this.size = size;

        ACell[][] grid = gui.core.level.data().grid();
        for (int y = 0; y < grid.length; y++) {
            for (int x = 0; x < grid[y].length; x++) {
                PicrossCell cell = new PicrossCell(grid[y][x].color(), size);
                add(cell);
            }
        }

        initComponents();
    }

    @Override
    public void setLayout(LayoutManager mgr) {
        if (gui != null) {
            ACell[][] grid = gui.core.level.data().grid();
            super.setLayout(new GridLayout(grid[0].length, grid.length));
        } else {
            super.setLayout(mgr);
        }
    }

    @Override
    public Dimension getPreferredSize() {
        ACell[][] grid = gui.core.level.data().grid();
        return new Dimension(grid[0].length * size, grid.length * size);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
